issuer: http://dex.auth.svc.cluster.local:5556/dex
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
oauth2:
  skipApprovalScreen: true
enablePasswordDB: false
staticClients:

- idEnv: OIDC_CLIENT_ID
  redirectURIs: ["/login/oidc"]
  name: 'Dex Login Application'
  secretEnv: OIDC_CLIENT_SECRET
connectors:
- type: ldap

  id: ldap
  name: LDAP
  config:
    host: dc01.eecs.net:389
    insecureNoSSL: true
    insecureSkipVerify: true
    startTLS: false
    bindDN: k8s_service@eecs.net
    bindPW: PASSWORD!!!
    usernamePrompt: EECSNet Username (first.last)
    userSearch:
      baseDN: ou=Faculty,dc=eecs,dc=net
      username: sAMAccountName
      idAttr: sAMAccountName
      emailAttr: userPrincipalName
      nameAttr: sAMAccountName